version: '3.8'

services:
  react-app:
    build: ./client
    container_name: client_c
    env_file:
      - ./client/.env
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mern-app
    depends_on:
      - nest-app

  nest-app:
    build: ./server
    container_name: server_c
    env_file:
      - ./server/.env
    volumes:
      - ./server/src:/app/src
      - staticdata:/app/dist/static
    links:
      - redis
    networks:
      - mern-app
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:1.21
    container_name: nginx_c
    ports:
      - '5000:80'
    volumes:
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - staticdata:/static
    networks:
      - mern-app
    depends_on:
      - nest-app

  mongo:
    image: mongo
    container_name: mongo_c
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-app

  mongo-express:
    image: mongo-express
    container_name: mongo-express_c
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
      - mern-app
    depends_on:
      - mongo

  redis:
    image: 'redis:alpine'
    container_name: redis_c
    ports:
      - '6379:6379'
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge

volumes:
  staticdata:
  mongo-data:
    driver: local
